name: Auto Build

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - uses: actions/checkout@v2

    - name: Build
      run: dotnet build -c release