name: Release

on:
  workflow_dispatch:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - uses: microsoft/setup-msbuild@v1.1

    - uses: actions/checkout@v2

    - name: Build
      run: |
        dotnet restore
        msbuild /t:publish /p:Configuration=Release /p:PublishProfile=ClickOnceProfile /p:RuntimeIdentifier=win-x64 /p:ApplicationVersion=2.0.1.${{github.run_number}} /p:MinimumRequiredVersion=2.0.1.${{github.run_number}} /p:PublishDir=bin\publish
        mkdir upload
        move "Rclone Mount\bin\publish\Rclone Mount.application" upload
        move "Rclone Mount\bin\publish\Application Files" ".\upload\Application Files"
        Invoke-WebRequest -Uri https://downloads.rclone.org/v1.59.2/rclone-v1.59.2-windows-amd64.zip -OutFile rclone.zip
        Expand-Archive rclone.zip -DestinationPath .
        rclone-v1.59.2-windows-amd64\rclone.exe move upload :s3:dustypig/bin/rclone_mount --s3-provider Wasabi --s3-endpoint s3.us-central-1.wasabisys.com --s3-access-key-id ${{secrets.S3_KEY}} --s3-secret-access-key ${{secrets.S3_SECRET}}

